  # name: dockerdocker

  # on: pull_request
  #  branches:
  #     - dev
  # jobs:
  #   docker-ci:
  #     needs: front-test
  #     # if: github.ref == 'refs/heads/dev'
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v2
  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v2
  #       - name: Login to Docker Hub
  #         uses: docker/login-action@v2
  #         with:
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       - name: Build and push
  #         uses: docker/build-push-action@v4
  #         with:
  #           push: true
  #           tags: keopsepikeco/epikeco_front:latest
